services:
  - type: web
    name: springboot-app
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    region: oregon
    branch: main
    autoDeploy: true
